version: '3'
services:
  redis:
    image: redis:alpine
    command: redis-server --appendonly yes
    volumes:
      - ./data:/data
    restart:
      always
  app:
    build: .
    links:
      - redis
    environment:
      - REDIS_URL=redis://redis
      - HOST=0.0.0.0
      - PORT=3000
    restart:
      always
